### ISSUE TITLE
dotnet命令不支持啊

### ISSUE THREAD

**Issue by 0611163** [lane-cn/stat#18]
命令：/bin/sh -c 'cd /home/server/dotnet/webapitest && dotnet Net6WebApiTest.dll --environment=Development'
这条命令在Linux系统手动执行是可以的。但是使用stathub创建应用，也是这个运行命令，就不支持，应用不断重启，也不报错。
除了java，python和docker都支持，为什么dotnet不支持呢

**Comment by rm-vrf** [comment]
程序需要挂在前台才可以执行，否则守护程序就会认为程序已经结束了，不断的启动它。容器技术也是这样的特性，Entrypoint必须是一个挂在前台执行的命令。

**Comment by 0611163** [comment]
我在/bin目录下创建了一个dotnet链接，就可以了。

**Comment by 0611163** [comment]
问题已解决。

**Comment by 0611163** [comment]
问题已解决。
