### ISSUE TITLE
stathub为什么star这么少呢？

### ISSUE THREAD

**Issue by 0611163** [lane-cn/stat#19]
我感觉stathub是一个非常有用的系统，管理应用非常方便，但为什么star这么少呢？难道有比stathub更好的东西？

**Comment by rm-vrf** [comment]
多谢关注，做这个项目让我收获很多。但是后来关注了Portainer这样的容器管理应用，就感觉继续做下去已经没有什么意思了。使用容器技术，才能提供一个不可变的运行环境。并且Docker技术提供了网络和存储接口，能做的事情有很多。

**Comment by 0611163** [comment]
我们公司用这个管理了100多个服务。有springboot、spark、docker+python。源码同事改过一点。
